version: '3'
services:
  sw-web:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ./www:/www
      - ./cnf/site.conf:/etc/nginx/conf.d/default.conf
  sw-php:
    build: 
      context: .
      dockerfile: php74mysql.dockerfile
    volumes:
      - ./www:/www
  sw-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test123
